
require('./assets/scripts/TileBlock');
require('./assets/scripts/adMgr');
require('./assets/scripts/game_config_dyn');
require('./assets/scripts/game_constants');
require('./assets/scripts/game_core');
require('./assets/scripts/game_helpers');
require('./assets/scripts/game_level_cfg');
require('./assets/scripts/game_main');
require('./assets/scripts/game_model');
require('./assets/scripts/global_model');
require('./assets/scripts/how_to_play_game');
require('./assets/scripts/jhsD3BQUzrckXHMC');
require('./assets/scripts/koffTaS');
require('./assets/scripts/level_item');
require('./assets/scripts/level_mgr');
require('./assets/scripts/loading');
require('./assets/scripts/model_base');
require('./assets/scripts/pool_manager');
